trigger:
  batch: true
  branches:
    include: 
    - 'master'
  paths:
    include: 
    - /
    
pr: none

pool:
  vmImage: 'ubuntu-latest'
#pool: self-hosted # If you are running self-hosted Azure DevOps Agents

stages:
# Refering the pipeline template, input parameter that are not specified will be added with defaults
- template: ./buildspec.yml
  parameters:
    serviceConnectionName: eks
    awsRegion: us-east-1
    awsEKSClusterName: demo
    projectName: webapp